#' Generic Method for Rt Analysis
#'
#' Computes the time-varying reproduction number (Rt), defined as the average
#' number of secondary infections generated by each infected individual at time
#' t, accounting for the generation interval distribution:
#' \deqn{R_t = \frac{I_t}{\sum_{k=0}^{\tau_{\max}-1} I_{t-k} \cdot \frac{g(k)}{g_a}}}
#'
#' Where:
#' \itemize{
#'   \item \eqn{I_t = \exp(\log\text{-incidence}_t)} is the current incidence
#'   \item \eqn{g(k)} is the generation interval probability for day k
#'   \item \eqn{g_a = \sum_{k=0}^{\tau_{\max}-1} g(k)} is the normalization
#'    constant
#'   \item \eqn{\tau_{\max}} is the maximum generation interval in days
#' }
#'
#' This metric quantifies **current transmission potential** by comparing present
#' incidence to the weighted historical incidence that could have generated it,
#' where:
#' \itemize{
#'   \item \eqn{R_t > 1}: Epidemic is growing (each case generates >1 secondary
#'    case)
#'   \item \eqn{R_t = 1}: Epidemic is stable (replacement level transmission)
#'   \item \eqn{R_t < 1}: Epidemic is declining (each case generates <1
#'   secondary case)
#'   \item Threshold of 1 is epidemiologically meaningful for control decisions
#' }
#'
#' **Generation interval considerations**:
#' \itemize{
#'   \item Accounts for transmission timing using probability distribution
#'   \eqn{g(k)}
#'   \item Recent cases contribute more to current transmission potential
#'   \item Accepts user-defined generation interval distributions
#' }
#'
#' This metric function can be run directly on the fitted model output.
#'
#' @param fitted_model Fitted model object with class `EpiStrainDynamics.fit`
#' @param tau_max Integer maximum generation interval in days (default: 7)
#' @param gi_dist Function that returns generation interval probability for given day
#' @param ... Additional arguments passed to metrics calculation
#' @return named list of class `EpiStrainDynamics.metric` containing a dataframe
#'  of the calculated metric outcome (`$measure`), the fit object (`$fit`), and the
#'  constructed model object (`$constructed_model`). The `measure` data frame
#'  contains the median of the epidemiological quantity (`y`), the 50% credible
#'  interval of the quantity (`lb_50` & `ub_50`), the 95% credible interval
#'  (`lb_95` & `ub_95`), the proportion greater than a defined threshold value
#'  (`prop`), the pathogen name (`pathogen`), and the time label (`time`).
#' @family metrics
#' @export
#'
#' @srrstats {G1.3} metric defined clearly
#' @srrstats {G1.4} uses `Roxygen2` documentation
#'
#' @examples
#' \dontrun{
#'   mod <- construct_model(
#'     method = random_walk(),
#'     pathogen_structure = single(
#'       case_timeseries = sarscov2$cases,
#'       time = sarscov2$date))
#'
#'   fit <- fit_model(mod)
#'
#'   rt <- Rt(fit, tau_max = 7, gi_dist = function(x) 4*x*exp(-2*x))
#' }
#'
Rt <- function(fitted_model, tau_max = 7, gi_dist, ...) {
  validate_class_inherits(fitted_model, 'EpiStrainDynamics.fit')
  UseMethod("Rt")
}

#' @rdname Rt
#' @export
Rt.ps <- function(fitted_model, tau_max = 7, gi_dist, ...) {
  g_a <- sum(gi_dist(seq(0, tau_max - 1, 1)))
  out <- compute_multi_pathogen(fitted_model, tau_max, 'Rt',
                                threshold = 1, use_splines = TRUE,
                                tau_max = tau_max, gi_dist = gi_dist, g_a = g_a)
  class(out) <- c('Rt', 'EpiStrainDynamics.metric', class(out))
  out
}

#' @rdname Rt
#' @export
Rt.rw <- function(fitted_model, tau_max = 7, gi_dist, ...) {
  g_a <- sum(gi_dist(seq(0, tau_max - 1, 1)))
  out <- compute_multi_pathogen(fitted_model, tau_max, 'Rt',
                                threshold = 1, use_splines = FALSE,
                                tau_max = tau_max, gi_dist = gi_dist, g_a = g_a)
  class(out) <- c('Rt', 'EpiStrainDynamics.metric', class(out))
  out
}

#' @rdname Rt
#' @export
Rt.ps_single <- function(fitted_model, tau_max = 7, gi_dist, ...) {
  g_a <- sum(gi_dist(seq(0, tau_max - 1, 1)))
  out <- compute_single_pathogen(fitted_model, tau_max, 'Rt',
                                 threshold = 1, use_splines = TRUE,
                                 tau_max = tau_max, gi_dist = gi_dist, g_a = g_a)
  class(out) <- c('Rt', 'EpiStrainDynamics.metric', class(out))
  out
}

#' @rdname Rt
#' @export
Rt.rw_single <- function(fitted_model, tau_max = 7, gi_dist, ...) {
  g_a <- sum(gi_dist(seq(0, tau_max - 1, 1)))
  out <- compute_single_pathogen(fitted_model, tau_max, 'Rt',
                                 threshold = 1, use_splines = FALSE,
                                 tau_max = tau_max, gi_dist = gi_dist, g_a = g_a)
  class(out) <- c('Rt', 'EpiStrainDynamics.metric', class(out))
  out
}

# =====================
# CALCULATION FUNCTIONS
# =====================

#' Calculate Rt for Single Pathogen Model
#'
#' Computes reproduction number for single pathogen models
#'
#' @param a Array of log-incidence posterior samples \code{[samples, time]}
#' @param time_idx Integer time index
#' @param pathogen_idx NULL (unused but required for interface consistency)
#' @param post Posterior samples object (unused but required for interface consistency)
#' @param components Model components (unused but required for interface consistency)
#' @param tau_max Integer maximum generation interval (days)
#' @param gi_dist Function returning generation interval probability for given day
#' @param g_a Numeric normalization constant (sum of generation interval)
#'
#' @return Vector of Rt posterior samples
#' @noRd
#'
#' @srrstats {G1.4} uses `Roxygen2` documentation
#' @srrstats {G1.4a} internal function specified with `@noRd`
#'
calc_rt_single <- function(a, time_idx, pathogen_idx, post, components,
                           tau_max, gi_dist, g_a) {

  R_denom <- matrix(0, nrow = length(a[, 1]), ncol = 1)
  for(k in 0:(tau_max - 1)) {
    R_denom <- R_denom + exp(a[, time_idx - k]) * gi_dist(k)
  }

  exp(a[, time_idx]) / (R_denom / g_a)
}

#' Calculate Rt for Individual Pathogen
#'
#' Computes reproduction number for a specific pathogen using generation interval convolution
#'
#' @param a Array of log-incidence posterior samples \code{[samples, pathogens, time]}
#' @param time_idx Integer time index
#' @param pathogen_idx Integer pathogen index
#' @param post Posterior samples object (unused but required for interface consistency)
#' @param components Model components (unused but required for interface consistency)
#' @param tau_max Integer maximum generation interval (days)
#' @param gi_dist Function returning generation interval probability for given day
#' @param g_a Numeric normalization constant (sum of generation interval)
#'
#' @return Vector of Rt posterior samples
#' @noRd
#'
#' @srrstats {G1.4} uses `Roxygen2` documentation
#' @srrstats {G1.4a} internal function specified with `@noRd`
#'
calc_rt_individual <- function(a, time_idx, pathogen_idx, post, components,
                               tau_max, gi_dist, g_a) {

  R_denom <- matrix(0, nrow = dim(a)[1], ncol = 1)
  for(k in 0:(tau_max - 1)) {
    R_denom <- R_denom + exp(a[, pathogen_idx, time_idx - k]) * gi_dist(k)
  }
  exp(a[, pathogen_idx, time_idx]) / (R_denom / g_a)
}

#' Calculate Total Rt Across All Pathogens
#'
#' Computes total reproduction number across all pathogens
#'
#' @param a Array of log-incidence posterior samples \code{[samples, pathogens, time]}
#' @param time_idx Integer time index
#' @param pathogen_idx NULL (unused but required for interface consistency)
#' @param post Posterior samples object (unused but required for interface consistency)
#' @param components Model components (unused but required for interface consistency)
#' @param tau_max Integer maximum generation interval (days)
#' @param gi_dist Function returning generation interval probability for given day
#' @param g_a Numeric normalization constant (sum of generation interval)
#'
#' @return Vector of total Rt posterior samples
#' @noRd
#'
#' @srrstats {G1.4} uses `Roxygen2` documentation
#' @srrstats {G1.4a} internal function specified with `@noRd`
#'
calc_rt_total <- function(a, time_idx, pathogen_idx, post, components,
                          tau_max, gi_dist, g_a) {

  R_denom <- matrix(0, nrow = dim(a)[1], ncol = 1)
  for(k in 0:(tau_max - 1)) {
    R_denom <- R_denom + rowSums(exp(a[, , time_idx - k])) * gi_dist(k)
  }
  rowSums(exp(a[, , time_idx])) / (R_denom / g_a)
}
